2025-10-28 00:00:00:INFO:Performing scheduled database backup.
2025-10-28 00:00:00:INFO:Deleting oldest backup /root/.local/share/spoolman/backups/spoolman.db.5
2025-10-28 00:00:00:INFO:Backing up SQLite database to /root/.local/share/spoolman/backups/spoolman.db
2025-10-28 00:00:00:INFO:Copied 1 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 2 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 3 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 4 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 5 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 6 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 7 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 8 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 9 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 10 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 11 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 12 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 13 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 14 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 15 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 16 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 17 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 18 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 19 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 20 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 21 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 22 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 23 of 24 pages.
2025-10-28 00:00:00:INFO:Copied 24 of 24 pages.
2025-10-28 00:00:00:INFO:Backup complete.
2025-10-28 00:10:28:INFO:Syncing external DB.
2025-10-28 00:10:28:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 00:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 00:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 01:10:28:INFO:Syncing external DB.
2025-10-28 01:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 01:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 01:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 02:10:28:INFO:Syncing external DB.
2025-10-28 02:10:28:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 02:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 02:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 03:10:28:INFO:Syncing external DB.
2025-10-28 03:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 03:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 03:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 04:10:28:INFO:Syncing external DB.
2025-10-28 04:10:28:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 04:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 04:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 05:10:28:INFO:Syncing external DB.
2025-10-28 05:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 05:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 05:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 06:10:28:INFO:Syncing external DB.
2025-10-28 06:10:28:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 06:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 06:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 07:10:28:INFO:Syncing external DB.
2025-10-28 07:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 07:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 07:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 08:10:28:INFO:Syncing external DB.
2025-10-28 08:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 08:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 08:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 09:10:28:INFO:Syncing external DB.
2025-10-28 09:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 09:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 09:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 10:10:28:INFO:Syncing external DB.
2025-10-28 10:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 10:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 10:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 11:10:28:INFO:Syncing external DB.
2025-10-28 11:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 11:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 11:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 12:10:28:INFO:Syncing external DB.
2025-10-28 12:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 12:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 12:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 12:46:06:INFO:Client 192.168.1.102 has stopped listening on pool spool
2025-10-28 12:46:09:INFO:Client 192.168.1.102 is now listening on pool spool
2025-10-28 13:10:28:INFO:Syncing external DB.
2025-10-28 13:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 13:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 13:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 13:18:37:INFO:Client 192.168.1.102 has stopped listening on pool spool
2025-10-28 13:18:49:INFO:Client 192.168.1.102 is now listening on pool spool
2025-10-28 14:10:28:INFO:Syncing external DB.
2025-10-28 14:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 14:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 14:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 14:31:03:INFO:Client 192.168.1.102 has stopped listening on pool spool
2025-10-28 14:32:02:INFO:Client 192.168.1.128 is now listening on pool spool
2025-10-28 14:33:32:INFO:Client 192.168.1.128 has stopped listening on pool spool
2025-10-28 14:33:49:INFO:Client 192.168.1.102 is now listening on pool spool
2025-10-28 14:42:20:INFO:Client 192.168.1.102 has stopped listening on pool spool
2025-10-28 15:10:28:INFO:Syncing external DB.
2025-10-28 15:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 15:10:29:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 15:10:29:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 15:36:11:INFO:Client 192.168.1.102 is now listening on pool spool
2025-10-28 16:01:44:INFO:Client 192.168.1.102 has stopped listening on pool spool
2025-10-28 16:10:28:INFO:Syncing external DB.
2025-10-28 16:10:33:ERROR:Unhandled exception in `scheduler.asyncio.job.Job(<JobType.CYCLIC: 1>, [datetime.timedelta(seconds=3600)], <function _sync at 0x778f1a1f42c0>, (), {}, 0, True, datetime.datetime(2025, 10, 22, 16, 10, 28, 928805), None, False, None, None)`!
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/scheduler/asyncio/job.py", line 64, in _exec
    await coroutine
  File "/opt/spoolman/spoolman/externaldb.py", line 174, in _sync
    filaments = _parse_filaments_from_bytes(await _download_file(urljoin(url, "filaments.json")))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spoolman/spoolman/externaldb.py", line 139, in _download_file
    response = await client.get(url)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1768, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/hishel/_async/_transports.py", line 162, in handle_async_request
    revalidation_response = await self._transport.handle_async_request(revalidation_request)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
2025-10-28 17:10:28:INFO:Syncing external DB.
2025-10-28 17:10:33:ERROR:Unhandled exception in `scheduler.asyncio.job.Job(<JobType.CYCLIC: 1>, [datetime.timedelta(seconds=3600)], <function _sync at 0x778f1a1f42c0>, (), {}, 0, True, datetime.datetime(2025, 10, 22, 16, 10, 28, 928805), None, False, None, None)`!
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/scheduler/asyncio/job.py", line 64, in _exec
    await coroutine
  File "/opt/spoolman/spoolman/externaldb.py", line 174, in _sync
    filaments = _parse_filaments_from_bytes(await _download_file(urljoin(url, "filaments.json")))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spoolman/spoolman/externaldb.py", line 139, in _download_file
    response = await client.get(url)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1768, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/hishel/_async/_transports.py", line 162, in handle_async_request
    revalidation_response = await self._transport.handle_async_request(revalidation_request)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
2025-10-28 18:10:28:INFO:Syncing external DB.
2025-10-28 18:10:33:ERROR:Unhandled exception in `scheduler.asyncio.job.Job(<JobType.CYCLIC: 1>, [datetime.timedelta(seconds=3600)], <function _sync at 0x778f1a1f42c0>, (), {}, 0, True, datetime.datetime(2025, 10, 22, 16, 10, 28, 928805), None, False, None, None)`!
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_async/connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/scheduler/asyncio/job.py", line 64, in _exec
    await coroutine
  File "/opt/spoolman/spoolman/externaldb.py", line 174, in _sync
    filaments = _parse_filaments_from_bytes(await _download_file(urljoin(url, "filaments.json")))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spoolman/spoolman/externaldb.py", line 139, in _download_file
    response = await client.get(url)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1768, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/hishel/_async/_transports.py", line 162, in handle_async_request
    revalidation_response = await self._transport.handle_async_request(revalidation_request)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/dist-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
2025-10-28 18:17:48:INFO:Starting Spoolman v0.22.1 (commit: 1888240) (built: 2025-03-18 20:42:38+00:00)
2025-10-28 18:17:48:INFO:Using data directory: /root/.local/share/spoolman
2025-10-28 18:17:48:INFO:Using logs directory: /root/.local/share/spoolman
2025-10-28 18:17:48:INFO:Using backups directory: /root/.local/share/spoolman/backups
2025-10-28 18:17:48:INFO:Setting up database...
2025-10-28 18:17:48:INFO:No database type specified, using a default SQLite database located at "/root/.local/share/spoolman/spoolman.db"
2025-10-28 18:17:48:INFO:Performing migrations...
2025-10-28 18:17:48:INFO:Scheduling automatic database backup for midnight.
2025-10-28 18:17:48:INFO:Scheduling external DB sync.
2025-10-28 18:17:48:INFO:Startup complete.
2025-10-28 18:17:48:INFO:Syncing external DB.
2025-10-28 18:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 18:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 18:17:49:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 18:17:50:INFO:Client 192.168.1.102 is now listening on pool spool
2025-10-28 19:17:48:INFO:Syncing external DB.
2025-10-28 19:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 19:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 19:17:49:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 20:04:20:INFO:Client 192.168.1.102 has stopped listening on pool spool
2025-10-28 20:06:15:INFO:Client 192.168.1.102 is now listening on pool spool
2025-10-28 20:17:48:INFO:Syncing external DB.
2025-10-28 20:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 20:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 20:17:49:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 21:17:48:INFO:Syncing external DB.
2025-10-28 21:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 21:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 21:17:49:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 21:23:18:INFO:Client 192.168.1.102 has stopped listening on pool spool
2025-10-28 22:01:49:INFO:Client 192.168.1.102 is now listening on pool spool
2025-10-28 22:17:48:INFO:Syncing external DB.
2025-10-28 22:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 22:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 22:17:49:INFO:External DB synced. Filaments: 6325, Materials: 32
2025-10-28 23:17:48:INFO:Syncing external DB.
2025-10-28 23:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/filaments.json "HTTP/1.1 200 OK"
2025-10-28 23:17:49:INFO:HTTP Request: GET https://donkie.github.io/SpoolmanDB/materials.json "HTTP/1.1 200 OK"
2025-10-28 23:17:49:INFO:External DB synced. Filaments: 6325, Materials: 32
